-- 在 Supabase 的 SQL Editor 執行本檔內容。

create table if not exists public.checklist_items (
  id bigint generated by default as identity primary key,
  checklist_key text not null,
  item_id text not null,
  item_title text not null,
  completed boolean not null default false,
  updated_at timestamptz not null default now(),
  unique (checklist_key, item_id)
);

alter table public.checklist_items enable row level security;

-- 簡易公開版：任何拿到網站網址的人都能讀取與修改檢核狀態。
-- 適合個人或小型團隊使用；不要存放敏感資料。

drop policy if exists "public read checklist" on public.checklist_items;
create policy "public read checklist"
on public.checklist_items
for select
to anon
using (true);

drop policy if exists "public insert checklist" on public.checklist_items;
create policy "public insert checklist"
on public.checklist_items
for insert
to anon
with check (true);

drop policy if exists "public update checklist" on public.checklist_items;
create policy "public update checklist"
on public.checklist_items
for update
to anon
using (true)
with check (true);
