
create table if not exists public.checklist_items (
  id bigint generated by default as identity primary key,
  checklist_key text not null,
  item_id text not null,
  item_title text not null,
  status text not null default 'todo'
    check (status in ('done','doing','todo','na')),
  note text not null default '',
  updated_at timestamptz not null default now(),
  unique (checklist_key, item_id)
);

alter table public.checklist_items add column if not exists status text not null default 'todo';
alter table public.checklist_items add column if not exists note text not null default '';

create table if not exists public.checklist_meta (
  checklist_key text primary key,
  completed_summary text not null default '',
  pending_summary text not null default '',
  next_summary text not null default '',
  target_date date,
  result text not null default '',
  updated_at timestamptz not null default now()
);

alter table public.checklist_items enable row level security;
alter table public.checklist_meta enable row level security;

drop policy if exists "public read checklist items" on public.checklist_items;
create policy "public read checklist items" on public.checklist_items for select to anon using (true);
drop policy if exists "public insert checklist items" on public.checklist_items;
create policy "public insert checklist items" on public.checklist_items for insert to anon with check (true);
drop policy if exists "public update checklist items" on public.checklist_items;
create policy "public update checklist items" on public.checklist_items for update to anon using (true) with check (true);

drop policy if exists "public read checklist meta" on public.checklist_meta;
create policy "public read checklist meta" on public.checklist_meta for select to anon using (true);
drop policy if exists "public insert checklist meta" on public.checklist_meta;
create policy "public insert checklist meta" on public.checklist_meta for insert to anon with check (true);
drop policy if exists "public update checklist meta" on public.checklist_meta;
create policy "public update checklist meta" on public.checklist_meta for update to anon using (true) with check (true);
